apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huginn-storage-claim
  labels:
    app: huginn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn-db
  labels:
    app: huginn
spec:
  replicas: 1
  selector:
    matchLabels:
      pod-label: huginn-db-pod
  template:
    metadata:
      labels:
        pod-label: huginn-db-pod
    spec:
      containers:
      - name: postgres
        image: postgres:12
        env:
        - name: POSTGRES_DB
          value: huginn
        envFrom:
        - secretRef:
            name: huginn-db-secret
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: huginn-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: huginn-db
  labels:
    app: huginn
spec:
  selector:
    pod-label: huginn-db-pod
  ports:
  - protocol: TCP
    port: 5432
