apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-shared-storage-claim
  labels:
    app: monica
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
